export const SET_REACT_FLOW_INSTANCE = "SET_REACT_FLOW_INSTANCE";
export const SET_CLICKED_ELEMENT = "SET_CLICKED_ELEMENT";
export const SET_MINIMAP_DISPLAY = "SET_MINIMAP_DISPLAY";
export const SET_GROUPBAR_DISPLAY = "SET_GROUPBAR_DISPLAY";
export const SET_ZOOM= "SET_ZOOM";
export const SET_ROTATE_ALL_PATH= "SET_ROTATE_ALL_PATH";
export const SET_EDGE_TYPE= "SET_EDGE_TYPE";



