export const SET_PANEL_CONTEXT = "SET_PANEL_CONTEXT";
export const SET_ELEMENT_CONTEXT = "SET_ELEMENT_CONTEXT";
export const SET_MULTISELECTION_CONTEXT = "SET_MULTISELECTION_CONTEXT";
export const SET_OPEN_GROUP_PANEL = "SET_OPEN_GROUP_PANEL";
