export const SET_ACTIVE_PANEL = "SET_ACTIVE_PANEL";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const SET_ACTIVE_PROJECT = "SET_ACTIVE_PROJECT";
export const SET_COPIED_ELEMENTS = "SET_COPIED_ELEMENTS";


export const ADD_DASHBOARD = "ADD_DASHBOARD";
export const UPDATE_DASHBOARD = "UPDATE_DASHBOARD";
export const DELETE_DASHBOARD = "DELETE_DASHBOARD";
