export const SET_ACTIVE_PANEL = "SET_ACTIVE_PANEL";
export const ADD_PROJECT = "ADD_PROJECT";
export const SET_ACTIVE_PROJECT = "SET_ACTIVE_PROJECT";
export const ADD_NEW_FLOW_TO_PROJECT = "ADD_NEW_FLOW_TO_PROJECT";