
const name = "elements"
export const SET_ELEMENTS = `${name}/setElements`;
export const ADD_NEW_NODE = `${name}/addNewNode`;
export const PASTE_NODES = `${name}/pasteNodes`;
export const SET_ROTATE_ALL= `${name}/setRotateAll`;
export const SET_EXPAND_ALL = `${name}/setExpandAll`;
export const ROTATE_NODE = `${name}/rotateNode`;
export const ROTATE_MULTI_NODE = `${name}/rotateMultiNode`;
export const EXPAND_NODE= `${name}/expandNode`;
export const CHANGE_NODE_NAME= `${name}/changeNodeName`;
export const SET_NODE_ENABLE= `${name}/setNodeEnable`;
export const SET_NODE_ENABLE_MULTIPLE= `${name}/setNodeEnableMultiple`;
export const SET_OUTGOERS_ENABLE= `${name}/setOutgoersEnable`;
export const IMPORT_ELEMENTS= `${name}/importElements`;
export const CHANGE_EDGE_TYPE= `${name}/changeEdgeType`;
export const SET_ALL_NODES_DESELECT= `${name}/setAllNodesDeselect`;
export const SET_GROUP_SINGLE= `${name}/setGroupSingle`;
export const SET_GROUP_MULTIPLE= `${name}/setGroupMultiple`;
export const SELECT_NODES= `${name}/selectNodes`;
export const DELETE_GROUP_OF_ELEMENT= `${name}/deleteGroupOfElements`;
export const UPDATE_GROUP_OF_ELEMENT= `${name}/updateGroupOfElements`;
export const UPDATE_NODE_HANDLES= `${name}/updateNodeHandles`;