export const SET_REACT_FLOW_INSTANCE = "SET_REACT_FLOW_INSTANCE";
export const SET_ACTIVE_FLOW = "SET_ACTIVE_FLOW";
export const SET_MINIMAP_DISPLAY = "SET_MINIMAP_DISPLAY";
export const SET_GROUPBAR_DISPLAY = "SET_GROUPBAR_DISPLAY";
export const SET_ZOOM= "SET_ZOOM";
export const SET_ROTATE_ALL_PATH= "SET_ROTATE_ALL_PATH";
export const SET_WORKSPACE_EDGE_TYPE= "SET_EDGE_TYPE";
export const SET_PANE_CLICK_POSITION= "SET_PANE_CLICK_POSITION";
export const SET_THEME = "SET_THEME";

//
export const SET_CURRENT_FLOW_CONFIG = "SET_CURRENT_FLOW_CONFIG";
export const OPEN_FLOW = "OPEN_FLOW";
export const CLOSE_FLOW = "CLOSE_FLOW";
export const SET_CURRENT_FLOW_WORKSPACE = "SET_CURRENT_FLOW_WORKSPACE";
export const SET_CURRENT_FLOW_ELEMENT = "SET_CURRENT_FLOW_ELEMENT";
export const SET_CURRENT_FLOW_GROUPS = "SET_CURRENT_FLOW_GROUPS";


export const SET_CLOSE_ALL_GROUPS = "SET_CLOSE_ALL_GROUPS";


export const ADD_FLOW = "ADD_FLOW";
export const UPDATE_FLOW = "UPDATE_FLOW";
export const DELETE_FLOW = "DELETE_FLOW";
export const MERGE_FLOW = "MERGE_FLOW";

