export const LOAD_GROUPS = "LOAD_GROUPS";
export const ADD_GROUP = "ADD_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const ADD_NODE_TO_GROUP_SINGLE = "ADD_NODE_TO_SINGLE";
export const ADD_NODE_TO_GROUP_MULTIPLE = "ADD_NODE_TO_GROUP_MULTIPLE";
export const DELETE_NODE_CURRENT_GROUP = "DELETE_NODE_CURRENT_GROUP";
