export const GET_WORKSPACES = "GET_WORKSPACES";
export const CREATE_WORKSPACE = "CREATE_WORKSPACE";
export const EDIT_WORKSPACE = "EDIT_WORKSPACE";
export const DELETE_WORKSPACE = "DELETE_WORKSPACE";
export const SET_ACTIVE_WORKSPACE = "SET_ACTIVE_WORKSPACE";
